version: '2'
services:
 mysql:
  image: mysql
  container_name: pwcho2018-76511
  ports:
   - "3306:3306"
  environment: 
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=baza
   - MYSQL_USER=MBolba
   - MYSQL_PASSWORD=password
  networks: 
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.3

 java:
  image: pwcho23112018monika/lab7
  container_name: kontenerjava
  stdin_open: true
  tty: true
  depends_on:
     - mysql
  networks:
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.4
networks:
 Bridge-Zadanie-1:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 10.0.10.0/24
   



